const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const task=$('#task'),model=$('#model'),fusionButton=$('#fusion');let currentResult=null,pendingSave=null;
const options=items=>items.map(path=>`<option value="${path}">${path}</option>`).join('');
function goTo(step){$$('.screen').forEach(screen=>screen.classList.toggle('active',Number(screen.dataset.screen)===step));$$('.workflow button').forEach(button=>{const n=Number(button.dataset.step);button.classList.toggle('active',n===step);button.classList.toggle('complete',n<step)});window.scrollTo({top:0,behavior:'smooth'})}
function recentTasks(){try{return JSON.parse(localStorage.getItem('jetarmSavedTasks')||'[]')}catch{return[]}}
function applyResult(data,message){const t=data.trajectory_summary,w=data.waypoint_summary,total=t.total_samples||0,valid=t.valid_trajectory_samples||0;$('#total').textContent=total;$('#valid').textContent=valid;$('#rate').textContent=total?`${(valid/total*100).toFixed(1)}%`:'0%';$('#waypointCount').textContent=w.waypoint_count||0;$('#frame').textContent=`座標系：${w.coordinate_frame||'camera_relative'}`;$('#resultTitle').textContent='視覺示教軌跡已建立';$('#resultText').textContent=message;$('#summarySentence').textContent=`系統取得 ${valid} 個有效軌跡點，已完成深度融合與平滑處理。`;$('#handoffPath').textContent=data.simulation_archive?`模擬交接包：${data.simulation_archive}`:'已載入歷史軌跡';$('#previewNext').disabled=false}
function renderSavedTasks(){const records=recentTasks();$('#savedList').innerHTML=records.length?records.map((r,i)=>`<button class="saved-item" data-record="${i}"><strong>${r.name}</strong><small>${r.date} · ${r.valid} 個軌跡點</small></button>`).join(''):'<p class="hint">尚無標準任務。請先完成一次視覺示教。</p>';$$('.saved-item').forEach(item=>item.addEventListener('click',()=>{const record=records[Number(item.dataset.record)];currentResult=record.result;applyResult(currentResult,`已載入「${record.name}」，更換工件並確認定位後即可重新模擬。`);goTo(3)}))}
async function loadLists(){try{const[tasks,models,health]=await Promise.all([fetch('/api/tasks').then(r=>r.json()),fetch('/api/models').then(r=>r.json()),fetch('/api/health').then(r=>r.json())]);task.innerHTML=options(tasks.items);model.innerHTML=options(models.items);fusionButton.disabled=!tasks.items.length||!models.items.length;$('#systemStatus').innerHTML=`<span></span> ${health.status==='ready'?'本機服務已連線':'服務未連線'}`}catch{$('#systemStatus').textContent='本機服務未連線';fusionButton.disabled=true}}
async function runFusion(){fusionButton.disabled=true;const original=fusionButton.textContent;fusionButton.textContent='正在進行推論與深度融合…';try{const response=await fetch('/api/fusion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task:task.value,model:model.value})}),data=await response.json();if(!response.ok)throw new Error(data.detail||'軌跡建立失敗');currentResult=data;localStorage.setItem('jetarmRecentDraft',JSON.stringify({date:new Date().toISOString(),result:data}));applyResult(data,'本次示教已自動暫存；即使未加入任務庫，仍可保留本次結果。');goTo(3)}catch(error){alert(`無法建立軌跡：${error.message}`)}finally{fusionButton.disabled=false;fusionButton.textContent=original}}
$$('.mode-card[data-mode]').forEach(card=>card.addEventListener('click',()=>{const saved=card.dataset.mode==='saved';$('#teachingPanel').hidden=saved;$('#savedPanel').hidden=!saved;$('#buildTitle').textContent=saved?'載入已儲存任務':'建立視覺示教軌跡';$('#confirmMode').textContent=saved?'已儲存任務':'視覺示教';if(saved)renderSavedTasks();goTo(2)}));
$$('[data-next]').forEach(button=>button.addEventListener('click',()=>goTo(Number(button.dataset.next))));$$('[data-back]').forEach(button=>button.addEventListener('click',()=>goTo(Number(button.dataset.back))));fusionButton.addEventListener('click',runFusion);
$('#saveAfter').addEventListener('change',event=>{$('#taskName').disabled=!event.target.checked});$('#taskName').disabled=true;
$('#confirmExecute').addEventListener('click',()=>{pendingSave=$('#saveAfter').checked&&currentResult?{name:$('#taskName').value.trim()||'未命名視覺示教',date:new Date().toLocaleString('zh-TW'),valid:currentResult.trajectory_summary.valid_trajectory_samples||0,result:currentResult}:null;goTo(6)});
$('#finishDemo').addEventListener('click',()=>{if(pendingSave){const records=recentTasks();records.unshift(pendingSave);localStorage.setItem('jetarmSavedTasks',JSON.stringify(records.slice(0,10)))}pendingSave=null;currentResult=null;$('#saveAfter').checked=false;$('#taskName').disabled=true;goTo(1)});loadLists();
