const $=selector=>document.querySelector(selector);
const cornerNames=['left_bottom','right_bottom','right_top','left_top'];
const cornerLabels=['左下','右下','右上','左上'];
const state={image:null,corners:[],imageSize:[0,0]};

function draw(){const canvas=$('#boardCanvas'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);if(state.image)ctx.drawImage(state.image,0,0,canvas.width,canvas.height);if(!state.corners.length)return;ctx.lineWidth=Math.max(3,canvas.width/320);ctx.strokeStyle='#8f3f35';ctx.fillStyle='#8f3f35';ctx.beginPath();state.corners.forEach((point,index)=>{if(index===0)ctx.moveTo(...point);else ctx.lineTo(...point)});if(state.corners.length===4)ctx.closePath();ctx.stroke();state.corners.forEach((point,index)=>{ctx.beginPath();ctx.arc(point[0],point[1],Math.max(8,canvas.width/100),0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(13,canvas.width/60)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(index+1),point[0],point[1]);ctx.fillStyle='#8f3f35'});updateProgress()}
function updateProgress(){const count=state.corners.length;$('#cornerProgress').textContent=`${count} / 4`;$('#saveDetail').textContent=count===4?'可先儲存畫面校正，JetArm三點明天再補':`下一點：${cornerLabels[count]||'完成'}`}
function canvasPoint(event){const canvas=$('#boardCanvas'),rect=canvas.getBoundingClientRect();return[(event.clientX-rect.left)*canvas.width/rect.width,(event.clientY-rect.top)*canvas.height/rect.height]}
function showImage(image){state.image=image;state.imageSize=[image.naturalWidth,image.naturalHeight];const maxWidth=1280,scale=Math.min(1,maxWidth/image.naturalWidth);$('#boardCanvas').width=Math.round(image.naturalWidth*scale);$('#boardCanvas').height=Math.round(image.naturalHeight*scale);state.corners=[];$('#canvasEmpty').hidden=true;draw()}
function loadImage(file){if(!file)return;const image=new Image();image.onload=()=>showImage(image);image.src=URL.createObjectURL(file)}
async function captureLive(){const button=$('#captureLive'),original=button.textContent;button.disabled=true;button.textContent='擷取中…';try{const response=await fetch(`/api/camera/frame.jpg?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('即時相機尚未提供畫面');const blob=await response.blob(),image=new Image();image.onload=()=>{showImage(image);URL.revokeObjectURL(image.src)};image.src=URL.createObjectURL(blob)}catch(error){$('#saveStatus').textContent='無法擷取相機';$('#saveDetail').textContent=error.message}finally{button.disabled=false;button.textContent=original}}
function numberValue(id){const value=Number($(id).value);return Number.isFinite(value)?value:null}
function collectRobotPoints(){const result={},surfaceZ=numberValue('#surfaceHeight');for(const name of ['left_bottom','right_bottom','left_top']){const inputs=[...document.querySelectorAll(`[data-ref="${name}"]`)];const values=inputs.map(input=>input.value.trim()===''?null:Number(input.value));if(values.every(value=>value===null))continue;if(values[2]===null&&surfaceZ!==null)values[2]=surfaceZ;if(values.some(value=>value===null||!Number.isFinite(value)))throw new Error(`${cornerLabels[cornerNames.indexOf(name)]}的JetArm XY必須完整填寫；Z可填在參考點或工作板表面Z`);result[name]=values}const count=Object.keys(result).length;if(count!==0&&count!==3)throw new Error('JetArm三個參考點請全部填寫，或全部留白明天再補');return result}
function buildConfig(){const width=numberValue('#boardWidth'),height=numberValue('#boardHeight');if(!width||width<=0||!height||height<=0)throw new Error('請輸入有效的工作板寬度與長度');if(state.corners.length!==4)throw new Error('請依序完成四個工作板角點');const scaleX=state.imageSize[0]/$('#boardCanvas').width,scaleY=state.imageSize[1]/$('#boardCanvas').height;const imageCorners={};state.corners.forEach((point,index)=>imageCorners[cornerNames[index]]=[Number((point[0]*scaleX).toFixed(3)),Number((point[1]*scaleY).toFixed(3))]);return{schema_version:1,board_name:$('#boardName').value.trim()||'competition_workboard',board_width_mm:width,board_height_mm:height,image_size_px:state.imageSize,image_corners:imageCorners,robot_reference_points:collectRobotPoints(),surface_z_mm:numberValue('#surfaceHeight'),heights_mm:{down_dry_run_mm:numberValue('#downHeight')??30,up_safe_mm:numberValue('#upHeight')??80},process_detection:{line_min_displacement_mm:numberValue('#lineThreshold')??15,point_max_spread_mm:numberValue('#pointThreshold')??8}}}
function fillConfig(config){if(config.board_name)$('#boardName').value=config.board_name;if(config.board_width_mm)$('#boardWidth').value=config.board_width_mm;if(config.board_height_mm)$('#boardHeight').value=config.board_height_mm;if(config.surface_z_mm!==null&&config.surface_z_mm!==undefined)$('#surfaceHeight').value=config.surface_z_mm;$('#downHeight').value=config.heights_mm?.down_dry_run_mm??30;$('#upHeight').value=config.heights_mm?.up_safe_mm??80;$('#lineThreshold').value=config.process_detection?.line_min_displacement_mm??15;$('#pointThreshold').value=config.process_detection?.point_max_spread_mm??8;for(const[name,values]of Object.entries(config.robot_reference_points||{})){['x','y','z'].forEach((axis,index)=>{const input=document.querySelector(`[data-ref="${name}"][data-axis="${axis}"]`);if(input)input.value=values[index]})}const status=config.calibration_status;if(status==='ready'){$('#saveStatus').textContent='完整校正已載入';$('#saveDetail').textContent='若設備沒有移動，可直接沿用'}else if(status==='image_only'){$('#saveStatus').textContent='畫面校正已儲存';$('#saveDetail').textContent='明天連線後補上JetArm三個參考點'}}
async function loadConfig(){try{const config=await fetch('/api/calibration').then(response=>response.json());fillConfig(config)}catch{$('#saveStatus').textContent='無法讀取校正設定'}}

$('#imageInput').addEventListener('change',event=>loadImage(event.target.files[0]));$('#boardCanvas').addEventListener('click',event=>{if(!state.image||state.corners.length>=4)return;state.corners.push(canvasPoint(event));draw()});$('#undoCorner').addEventListener('click',()=>{state.corners.pop();draw();updateProgress()});$('#resetCorners').addEventListener('click',()=>{state.corners=[];draw();updateProgress()});$('#calibrationForm').addEventListener('submit',async event=>{event.preventDefault();try{const config=buildConfig();$('#saveStatus').textContent='儲存中…';const response=await fetch('/api/calibration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)}),result=await response.json();if(!response.ok)throw new Error(result.detail||'儲存失敗');const status=result.config.calibration_status;$('#saveStatus').textContent=status==='ready'?'完整校正已儲存':'畫面校正已儲存';$('#saveDetail').textContent=status==='ready'?'可進行30 mm高度安全空跑':'明天連線後補上JetArm三個參考點'}catch(error){$('#saveStatus').textContent='無法儲存';$('#saveDetail').textContent=error.message}});updateProgress();loadConfig();
$('#captureLive').addEventListener('click',captureLive);
